name: Deploy to GoDaddy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GoDaddy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: ALL # 👈 sends all GitHub repo secrets + variables to your server
          script: |
            # ensure folder exists
            mkdir -p ~/apps/cue-wellness-backend

            cd ~/apps/cue-wellness-backend
            if [ ! -d ".git" ]; then
              git clone git@github.com:sahilsheikh-dev/cue-wellness-backend.git .
            else
              git reset --hard
              git pull origin main
            fi
            npm install --production

            # restart app with environment from GitHub
            pm2 delete cue-wellness-backend || true
            pm2 start index.js --name cue-wellness-backend --update-env
