name: Deploy Cue Wellness Backend to GoDaddy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GoDaddy Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: ALL
          script: |
            # ensure folder exists
            mkdir -p ~/apps/cue-wellness-backend
            cd ~/apps/cue-wellness-backend

            # pull latest code
            if [ ! -d ".git" ]; then
              echo "First time setup: cloning repository"
              git clone git@github.com:sahilsheikh-dev/cue-wellness-backend.git .
            else
              echo "Pulling latest changes"
              git reset --hard
              git pull origin main
            fi

            # install dependencies (new recommended flag)
            echo "Installing dependencies"
            npm install --omit=dev

            # restart app with zero downtime using PM2 cluster mode
            echo "Reloading PM2 process"
            pm2 start index.js --name cue-wellness-backend -i max --update-env || true

            # restart app with zero downtime using PM2 cluster mode
            if pm2 describe cue-wellness-backend > /dev/null; then
              echo "Reloading existing PM2 process"
              pm2 reload cue-wellness-backend --update-env
            else
              echo "Starting new PM2 process"
              pm2 start index.js --name cue-wellness-backend -i max --update-env
            fi

            pm2 save
            pm2 status
            echo "Deployment completed successfully"
