name: Deploy Cue Wellness Backend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Deployment Timestamp
        run: echo "DEPLOY_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      # --- Setup SSH key once ---
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      # --- Capture Hostname from Server ---
      - name: Capture Hostname
        run: |
          HOSTNAME=$(ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "hostname")
          echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV
          echo "Captured Hostname: $HOSTNAME"

      # --- Deploy ---
      - name: Deploy to Server via SSH
        id: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: ALL
          script: |
            set -e
            mkdir -p ~/apps/cue-wellness-backend
            cd ~/apps/cue-wellness-backend

            echo "📦 Backing up PM2 process list"
            pm2 save
            cp ~/.pm2/dump.pm2 ~/.pm2/dump.pm2.bak || true

            if [ ! -d ".git" ]; then
              echo "🆕 First time setup: cloning repository"
              git clone git@github.com:sahilsheikh-dev/cue-wellness-backend.git .
            else
              echo "⬇️ Pulling latest changes"
              git reset --hard
              git pull origin main
            fi

            echo "📦 Installing dependencies"
            npm install --omit=dev

            if pm2 describe cue-wellness-backend > /dev/null; then
              echo "♻️ Reloading PM2 process"
              pm2 reload cue-wellness-backend --update-env
            else
              echo "🚀 Starting PM2 process"
              pm2 start index.js --name cue-wellness-backend -i max --update-env
            fi

            pm2 save
            pm2 status
            echo "✅ Deployment step completed"

      # --- Health Check ---
      - name: Health Check
        run: |
          echo "⏳ Waiting for backend..."
          for i in {1..10}; do
            if curl -skf https://backend.cuewellness.net/health; then
              echo "✅ Health check passed"
              exit 0
            else
              echo "⚠️ Attempt $i failed"
              sleep 5
            fi
          done
          echo "❌ Health check failed"
          exit 1

      # --- Rollback ---
      - name: Rollback if Health Check Failed
        if: failure() && steps.deploy.outcome == 'success'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🚨 Health check failed, rolling back..."
            if [ -f ~/.pm2/dump.pm2.bak ]; then
              cp ~/.pm2/dump.pm2.bak ~/.pm2/dump.pm2
              pm2 resurrect
              pm2 save
              echo "✅ Rollback completed"
            else
              echo "⚠️ No backup found!"
              exit 1
            fi

      # --- Fetch logs on failure ---
      - name: Fetch PM2 Logs on Failure
        if: failure()
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "pm2 logs cue-wellness-backend --lines 100 --nostream > ~/pm2_error.log || true"
          scp -o StrictHostKeyChecking=no -i id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/pm2_error.log ./pm2_error.log || true

      - name: Upload Logs Artifact (Failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pm2-error-logs
          path: ./pm2_error.log

      # --- Fetch status on success ---
      - name: Fetch PM2 Status on Success
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "pm2 status > ~/pm2_status.log; pm2 list >> ~/pm2_status.log; pm2 show cue-wellness-backend >> ~/pm2_status.log; node -v >> ~/pm2_status.log; npm -v >> ~/pm2_status.log; pm2 -v >> ~/pm2_status.log"
          scp -o StrictHostKeyChecking=no -i id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/pm2_status.log ./pm2_status.log || true

      - name: Upload Status Artifact (Success)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pm2-status-report
          path: ./pm2_status.log

      # --- Notify success ---
      - name: Notify Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Deployment Successful: Cue Wellness Backend on ${{ env.HOSTNAME }} (${{ secrets.SERVER_IP }})"
          html_body: |
            <h2>✅ Deployment Successful</h2>
            <p>The deployment to <b>${{ env.HOSTNAME }} (${{ secrets.SERVER_IP }})</b> was successful.</p>
            <p><b>Time:</b> ${{ env.DEPLOY_TIME }}</p>
            <p>
              <b>Commit:</b>
              <a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}">
                ${{ github.sha }}
              </a><br/>
              <b>Author:</b> ${{ github.actor }}<br/>
              <b>Message:</b> ${{ github.event.head_commit.message }}
            </p>
            <p>
              🌐 Host: <b>${{ env.HOSTNAME }}</b><br/>
              📡 IP: <b>${{ secrets.SERVER_IP }}</b><br/>
            </p>
            <p>
              🔍 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">
                View Full GitHub Actions Logs
              </a><br/>
              🌍 <a href="https://backend.cuewellness.net/">Visit Live Backend</a>
            </p>
            <p>📎 PM2 status report is attached.</p>
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          attachments: ./pm2_status.log

      # --- Notify failure ---
      - name: Notify Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Deployment Failed: Cue Wellness Backend on ${{ env.HOSTNAME }} (${{ secrets.SERVER_IP }})"
          html_body: |
            <h2>❌ Deployment Failed</h2>
            <p>The deployment to <b>${{ env.HOSTNAME }} (${{ secrets.SERVER_IP }})</b> failed.</p>
            <p><b>Time:</b> ${{ env.DEPLOY_TIME }}</p>
            <p>
              <b>Commit:</b>
              <a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}">
                ${{ github.sha }}
              </a><br/>
              <b>Author:</b> ${{ github.actor }}<br/>
              <b>Message:</b> ${{ github.event.head_commit.message }}
            </p>
            <p>
              🌐 Host: <b>${{ env.HOSTNAME }}</b><br/>
              📡 IP: <b>${{ secrets.SERVER_IP }}</b><br/>
            </p>
            <p>📎 PM2 error logs are attached.</p>
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          attachments: ./pm2_error.log
